### ISSUE TITLE
Unable to access full data dump

### ISSUE THREAD

**Issue by miriambudayr** [art-institute-of-chicago/api-data#1]
I am wondering if there is supposed to be more data in the `json/artworks` folder. I am trying to get all the artwork data the museum has available by using this repo. Thanks!

**Comment by IllyaMoskvin** [comment]
Hi @miriambudayr! Ah yes, sorry about that. This data is currently stale.

We ran into some issues with pushing our full dataset to GitHub, so we decided to upload it to AWS S3 instead, leaving only a sampler in this repo. Unfortunately, we had to shift our focus elsewhere before finishing that work. We have some time slotted in the near future to finish migrating the data dumps. I'll comment on this ticket once the data dump is restored.

Generally, I'd recommend against it for performance reasons, but since the data dump is not currently available, feel free to scrape our API for the data you need. Just go slow, use a single thread, keep the page size small, etc. You can find the API documentation here:

https://api.artic.edu/docs/

Thank you for reporting the issue. It's always nice to hear from folks looking to work with our data.

**Comment by dzbt** [comment]
Hi @IllyaMoskvin 
I read your comment above, and you say dump data on GitHub is not currently full.
And, you are advised to call the API even if you collect a lot of data.

I wanted to collect all the artwork information that AIC publishes in the public domain. 
When I called the artwork API, total number of public domain image data was 55199, and total pages was 1104.
However, the API does not return more than 10000 results.

Success: https://api.artic.edu/api/v1/artworks/search?limit=50&page=200&is_public_domain=true
Error: https://api.artic.edu/api/v1/artworks/search?limit=50&page=201&is_public_domain=true

Can't I get more than 10,000 results until you put the data on AWS S3?
Can you tell me if there is a way to get more than 10,000 results with the current API?

**Comment by IllyaMoskvin** [comment]
Hey everyone, thanks for your patience. We got the full dataset back online via AWS S3. The direct link might change in the future, so please check this repo's README for the link, currently located in the following section:

https://github.com/art-institute-of-chicago/api-data#where-is-the-full-dataset

@dzbt Yes, sorry about that. You are correct: it is not possible to obtain more than 10,000 results via our search API. However, with the full dataset now available, you should be able to download it and filter the artworks locally.

This is a good question, though. We've been collecting material for an FAQ section in our API documentation, and I think that the question of how to download data for all artworks that are in the public domain is a good topic to include.
