### ISSUE TITLE
Including Image URLs as part of the dataset?

### ISSUE THREAD

**Issue by gregsadetsky** [art-institute-of-chicago/api-data#2]
Hi,

Similarly to the Met, the Open Access dataset that's published by the Art Institute of Chicago does not include Image URLs -- "Images are not included and are not part of the dataset"

Are there plans to make the image urls part of the dataset?

For the time being, I've created a repository which -- through API calls -- links object number/ids and the corresponding image URLs here for both museums: https://github.com/gregsadetsky/open-access-is-great-but-where-are-the-images

I hope this can be useful. Thank you!

**Comment by IllyaMoskvin** [comment]
Thanks for flagging this! We actually _just_ added [instructions about how to access images](https://api.artic.edu/docs/#images) to our API documentation about two weeks ago. We'll update the README of this repository to better surface these instructions.

All of our image URLs follow certain patterns ([IIIF Image API v2](https://iiif.io/api/image/2.0/)). For example:

```
https://www.artic.edu/iiif/2/{image_id}/full/843,/0/default.jpg
```

If you replace `{image_id}` with the `image_id` field of an artwork:

```
https://api.artic.edu/api/v1/artworks?fields=id,title,image_id
```

...you'll get the same image as we display on artwork detail pages. For example, _The Bedroom_:

- https://www.artic.edu/artworks/28560/the-bedroom
- https://api.artic.edu/api/v1/artworks/28560?fields=id,title,image_id
- https://www.artic.edu/iiif/2/25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e/full/843,/0/default.jpg

I'm hesitant to include image URLs in API responses (and the data dumps) because these image URL patterns are the same for all artworks. Once you know one image URL, you know them all. You just need to swap out the image identifier.

But that said, I can see the value in providing fields with pre-baked image URLs. That way, users of our API wouldn't need to know about our [recommended image sizes](https://api.artic.edu/docs/#image-sizes) or the [International Image Interoperability Framework](https://iiif.io/) in order to access our images. We could offer URL fields for several image sizes: thumbnails, large, and full-sized. Each API client wouldn't have to reimplement this logic locally, and if we absolutely had to change our image URLs for some reason, those changes would automatically propagate to every client that used our recommended fields directly. 

So to answer your question—

> Are there plans to make the image urls part of the dataset?

Possibly! I'll check in with the team.

**Comment by gregsadetsky** [comment]
Thanks a lot for your response! Pre-baked image URLs as part of API responses seem (to me) like a good idea even if the URLs can be easily re-constructed.

I do think that including image URLs as part of the dataset that you are making available would be the best. That way, "everything" can be downloaded in one swoop.

Thanks again
